# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RadioVerdeTube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_radioVerdeGui(object):
    def setupUi(self, radioVerdeGui):
        radioVerdeGui.setObjectName("radioVerdeGui")
        radioVerdeGui.resize(325, 401)
        radioVerdeGui.setMinimumSize(QtCore.QSize(325, 401))
        radioVerdeGui.setMaximumSize(QtCore.QSize(325, 401))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./media/radTub.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        radioVerdeGui.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(radioVerdeGui)
        self.label.setGeometry(QtCore.QRect(125, 0, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./media/radTub.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(radioVerdeGui)
        self.line.setGeometry(QtCore.QRect(20, 80, 291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelUrlVideo = QtWidgets.QLabel(radioVerdeGui)
        self.labelUrlVideo.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.labelUrlVideo.setStyleSheet("font: 75 italic 10pt \"Verdana\";")
        self.labelUrlVideo.setObjectName("labelUrlVideo")

        self.labelUrlVideoErr = QtWidgets.QLabel(radioVerdeGui)
        self.labelUrlVideoErr.setGeometry(QtCore.QRect(150, 100, 135, 20))
        self.labelUrlVideoErr.setStyleSheet("font: 75 italic 10pt \"Verdana\";color:rgb(170, 0, 0);")
        self.labelUrlVideoErr.setObjectName("labelUrlVideoErr")

        self.lineUrlVideo = QtWidgets.QLineEdit(radioVerdeGui)
        self.lineUrlVideo.setGeometry(QtCore.QRect(10, 120, 301, 20))
        self.lineUrlVideo.setStyleSheet("font: 75 italic 8pt \"Verdana\";")
        self.lineUrlVideo.setObjectName("lineUrlVideo")
        self.lineNameFile = QtWidgets.QLineEdit(radioVerdeGui)
        self.lineNameFile.setGeometry(QtCore.QRect(10, 170, 301, 20))
        self.lineNameFile.setStyleSheet("font: 75 italic 8pt \"Verdana\";")
        self.lineNameFile.setText("")
        self.lineNameFile.setObjectName("lineNameFile")
        self.labelNameFile = QtWidgets.QLabel(radioVerdeGui)
        self.labelNameFile.setGeometry(QtCore.QRect(10, 150, 141, 20))
        self.labelNameFile.setStyleSheet("font: 75 italic 10pt \"Verdana\";")
        self.labelNameFile.setObjectName("labelNameFile")

        self.labelNameFileErr = QtWidgets.QLabel(radioVerdeGui)
        self.labelNameFileErr.setGeometry(QtCore.QRect(150, 150, 141, 20))
        self.labelNameFileErr.setStyleSheet("font: 75 italic 10pt \"Verdana\";color:rgb(170, 0, 0);")
        self.labelNameFileErr.setObjectName("labelNameFileErr")

        self.labelArtist = QtWidgets.QLabel(radioVerdeGui)
        self.labelArtist.setGeometry(QtCore.QRect(10, 200, 61, 20))
        self.labelArtist.setStyleSheet("font: 75 italic 10pt \"Verdana\";")
        self.labelArtist.setObjectName("labelArtist")

        self.labelArtistErr = QtWidgets.QLabel(radioVerdeGui)
        self.labelArtistErr.setGeometry(QtCore.QRect(130, 200, 100, 20))
        self.labelArtistErr.setStyleSheet("font: 75 italic 10pt \"Verdana\";color:rgb(170, 0, 0);")
        self.labelArtistErr.setObjectName("labelArtistErr")

        self.lineArtist = QtWidgets.QLineEdit(radioVerdeGui)
        self.lineArtist.setGeometry(QtCore.QRect(10, 220, 301, 20))
        self.lineArtist.setStyleSheet("font: 75 italic 8pt \"Verdana\";")
        self.lineArtist.setText("")
        self.lineArtist.setObjectName("lineArtist")
        self.labelFormat = QtWidgets.QLabel(radioVerdeGui)
        self.labelFormat.setGeometry(QtCore.QRect(10, 250, 61, 20))
        self.labelFormat.setStyleSheet("font: 75 italic 10pt \"Verdana\";")
        self.labelFormat.setObjectName("labelFormat")
        self.comboFormat = QtWidgets.QComboBox(radioVerdeGui)
        self.comboFormat.setGeometry(QtCore.QRect(80, 250, 51, 22))
        self.comboFormat.setStyleSheet("color:rgb(170, 0, 0)")
        self.comboFormat.setEditable(False)
        self.comboFormat.setObjectName("comboFormat")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.line_2 = QtWidgets.QFrame(radioVerdeGui)
        self.line_2.setGeometry(QtCore.QRect(20, 280, 291, 20))
        self.line_2.setMaximumSize(QtCore.QSize(291, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushClear = QtWidgets.QPushButton(radioVerdeGui)
        self.pushClear.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.pushClear.setObjectName("pushClear")
        self.pushDownload = QtWidgets.QPushButton(radioVerdeGui)
        self.pushDownload.setGeometry(QtCore.QRect(50, 330, 121, 23))
        self.pushDownload.setStyleSheet("font: 75 10pt \"Verdana\";")
        self.pushDownload.setObjectName("pushDownload")

        self.pushselectDir = QtWidgets.QPushButton(radioVerdeGui)
        self.pushselectDir.setGeometry(QtCore.QRect(90, 300, 150, 23))
        self.pushselectDir.setStyleSheet("font: 75 10pt \"Verdana\";")
        self.pushselectDir.setObjectName("pushselectDir")
        self.pushselectDir.setDefault(True)

        self.pushOpen = QtWidgets.QPushButton(radioVerdeGui)
        self.pushOpen.setGeometry(QtCore.QRect(180, 330, 75, 23))
        self.pushOpen.setStyleSheet("font: 75 10pt \"Verdana\";")
        self.pushOpen.setObjectName("pushOpen")

        self.label_2 = QtWidgets.QLabel(radioVerdeGui)
        self.label_2 = QtWidgets.QLabel(radioVerdeGui)
        self.label_2.setGeometry(QtCore.QRect(10, 370, 301, 20))
        self.label_2.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 10, 63)")
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(radioVerdeGui)
        self.line_3.setGeometry(QtCore.QRect(10, 360, 291, 20))
        self.line_3.setMaximumSize(QtCore.QSize(291, 16777215))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(radioVerdeGui)
        self.line_4.setGeometry(QtCore.QRect(10, 380, 291, 20))
        self.line_4.setMaximumSize(QtCore.QSize(291, 16777215))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(radioVerdeGui)
        self.pushClear.clicked.connect(self.lineArtist.clear)
        self.pushClear.clicked.connect(self.lineNameFile.clear)
        self.pushClear.clicked.connect(self.lineUrlVideo.clear)
        QtCore.QMetaObject.connectSlotsByName(radioVerdeGui)

    def retranslateUi(self, radioVerdeGui):
        _translate = QtCore.QCoreApplication.translate
        radioVerdeGui.setWindowTitle(_translate("radioVerdeGui", "Radio Verde Tube"))
        self.labelUrlVideo.setText(_translate("radioVerdeGui", "URL del Video:"))
        self.labelNameFile.setText(_translate("radioVerdeGui", "Nombre de Archivo:"))
        self.labelArtist.setText(_translate("radioVerdeGui", "Artista:"))
        self.labelFormat.setText(_translate("radioVerdeGui", "Formato:"))
        self.comboFormat.setItemText(0, _translate("radioVerdeGui", ".mp3"))
        self.comboFormat.setItemText(1, _translate("radioVerdeGui", ".wav"))
        self.comboFormat.setItemText(2, _translate("radioVerdeGui", ".aac"))
        self.pushClear.setText(_translate("radioVerdeGui", "Limpiar"))
        self.pushDownload.setText(_translate("radioVerdeGui", "Descargar Audio"))
        self.pushOpen.setText(_translate("radioVerdeGui", "Abrir"))
        self.pushselectDir.setText(_translate("radioVerdeGui", "Seleccionar Carpeta"))
        self.label_2.setText(_translate("radioVerdeGui", "Developed by: Emilio Lucero Loza,               Gualmatán-Nariño"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    radioVerdeGui = QtWidgets.QDialog()
    ui = Ui_radioVerdeGui()
    ui.setupUi(radioVerdeGui)
    radioVerdeGui.show()
    sys.exit(app.exec_())
