# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RadioVerdeTubeGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_radioVerdeGui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 469)
        Dialog.setMinimumSize(QtCore.QSize(435, 469))
        Dialog.setMaximumSize(QtCore.QSize(435, 469))
        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(435, 469))
        self.frame.setMaximumSize(QtCore.QSize(435, 469))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color:rgb(0,0,0);\n"
"}\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_superior)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setStyleSheet("background-color:rgb(255,222,222)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("media/radTub.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color:rgb(20,200,220);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(12, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_min.setStyleSheet("")
        self.btn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon)
        self.btn_min.setIconSize(QtCore.QSize(38, 38))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout.addWidget(self.btn_min)
        self.btn_min.setDefault(False)
        self.btn_close = QtWidgets.QPushButton(self.frame_superior)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(38, 38))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_medio = QtWidgets.QFrame(self.frame)
        self.frame_medio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_medio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_medio.setObjectName("frame_medio")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_medio)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_input = QtWidgets.QFrame(self.frame_medio)
        self.frame_input.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,79);\n"
"}\n"
"\n"
"QLabel{\n"
"font:97 12pt \'Arial Black\';\n"
"color:rgb(20,200,220);\n"
"border:0px solid #14C8DC;\n"
"}")
        self.frame_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName("frame_input")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_input)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_input1 = QtWidgets.QFrame(self.frame_input)
        self.frame_input1.setStyleSheet("QLabel{\n"
"font:97 12pt \'Arial Black\';\n"
"color:rgb(20,200,220);\n"
"border:0px solid #14C8DC;\n"
"}")
        self.frame_input1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input1.setObjectName("frame_input1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_input1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_input1)
        self.label_3.setStyleSheet("color:rgb(20,200,220);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineUrlVideo = QtWidgets.QLineEdit(self.frame_input1)
        self.lineUrlVideo.setStyleSheet("background-color:rgb(0,0,0);\n"
"color:rgb(200,200,220);\n"
"font: 75 italic 10pt \"Verdana\";")
        self.lineUrlVideo.setText("")
        self.lineUrlVideo.setObjectName("lineUrlVideo")
        self.verticalLayout_4.addWidget(self.lineUrlVideo)
        self.verticalLayout_7.addWidget(self.frame_input1)
        self.frame_input1_2 = QtWidgets.QFrame(self.frame_input)
        self.frame_input1_2.setStyleSheet("QLabel{\n"
"font:97 12pt \'Arial Black\';\n"
"color:rgb(20,200,220);\n"
"border:0px solid #14C8DC;\n"
"}")
        self.frame_input1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input1_2.setObjectName("frame_input1_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_input1_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_input1_2)
        self.label_4.setStyleSheet("color:rgb(20,200,220);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.lineNameFile = QtWidgets.QLineEdit(self.frame_input1_2)
        self.lineNameFile.setStyleSheet("background-color:rgb(0,0,0);\n"
"color:rgb(200,200,220);\n"
"font: 75 italic 10pt \"Verdana\";")
        self.lineNameFile.setText("")
        self.lineNameFile.setObjectName("lineNameFile")
        self.verticalLayout_5.addWidget(self.lineNameFile)
        self.verticalLayout_7.addWidget(self.frame_input1_2)
        self.frame_input1_3 = QtWidgets.QFrame(self.frame_input)
        self.frame_input1_3.setStyleSheet("QLabel{\n"
"font:97 12pt \'Arial Black\';\n"
"color:rgb(20,200,220);\n"
"border:0px solid #14C8DC;\n"
"}")
        self.frame_input1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input1_3.setObjectName("frame_input1_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_input1_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_input1_3)
        self.label_5.setStyleSheet("color:rgb(20,200,220);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineArtist = QtWidgets.QLineEdit(self.frame_input1_3)
        self.lineArtist.setStyleSheet("background-color:rgb(0,0,0);\n"
"color:rgb(200,200,220);\n"
"font: 75 italic 10pt \"Verdana\";")
        self.lineArtist.setText("")
        self.lineArtist.setObjectName("lineArtist")
        self.verticalLayout_6.addWidget(self.lineArtist)
        self.verticalLayout_7.addWidget(self.frame_input1_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_input)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setStyleSheet("color:rgb(20,200,220);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboFormat = QtWidgets.QComboBox(self.frame_2)
        self.comboFormat.setStyleSheet("color:rgb(200,200,220);\n"
"font: 75 italic 12pt \"Verdana\";\n"
"background-color:rgb(0,0,0);")
        self.comboFormat.setObjectName("comboFormat")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.comboFormat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboFormat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushClear = QtWidgets.QPushButton(self.frame_2)
        self.pushClear.setMinimumSize(QtCore.QSize(100, 0))
        self.pushClear.setStyleSheet("QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20,200,220);\n"
"border: 1px solid white;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"}")
        self.pushClear.setObjectName("pushClear")
        self.horizontalLayout_2.addWidget(self.pushClear)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame_input)
        self.verticalLayout_2.addWidget(self.frame_medio)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,79);\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_btns = QtWidgets.QFrame(self.frame_inferior)
        self.frame_btns.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,97);\n"
"}\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color:rgb(20,200,220);\n"
"border: 1px solid white;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"}")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_btns)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushSelectDir = QtWidgets.QPushButton(self.frame_btns)
        self.pushSelectDir.setObjectName("pushSelectDir")
        self.verticalLayout_8.addWidget(self.pushSelectDir)
        self.pushDownload = QtWidgets.QPushButton(self.frame_btns)
        self.pushDownload.setObjectName("pushDownload")
        self.verticalLayout_8.addWidget(self.pushDownload)
        self.pushOpen = QtWidgets.QPushButton(self.frame_btns)
        self.pushOpen.setObjectName("pushOpen")
        self.verticalLayout_8.addWidget(self.pushOpen)
        self.label_7 = QtWidgets.QLabel(self.frame_btns)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_7.setStyleSheet("color:rgb(250,230,23);\n"
"font: 75 9pt \"Nirmala UI\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.frame_btns)
        self.frame_img = QtWidgets.QFrame(self.frame_inferior)
        self.frame_img.setStyleSheet("background-color:black;")
        self.frame_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_img.setObjectName("frame_img")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_img)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_logo = QtWidgets.QLabel(self.frame_img)
        self.label_logo.setMinimumSize(QtCore.QSize(40, 40))
        self.label_logo.setMaximumSize(QtCore.QSize(250, 250))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("media/radTub.svg"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_4.addWidget(self.label_logo)
        self.horizontalLayout_3.addWidget(self.frame_img)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.btn_close.clicked.connect(Dialog.close) # type: ignore
        self.btn_min.clicked.connect(Dialog.showMinimized) # type: ignore
        self.pushClear.clicked.connect(self.lineUrlVideo.clear) # type: ignore
        self.pushClear.clicked.connect(self.lineNameFile.clear) # type: ignore
        self.pushClear.clicked.connect(self.lineArtist.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RadioVerdeTube"))
        self.label_3.setText(_translate("Dialog", "Url del Video:"))
        self.label_4.setText(_translate("Dialog", "Nombre del Archivo:"))
        self.label_5.setText(_translate("Dialog", "Artista"))
        self.label_6.setText(_translate("Dialog", "Formato de Salida"))
        self.comboFormat.setItemText(0, _translate("Dialog", ".mp3"))
        self.comboFormat.setItemText(1, _translate("Dialog", ".wav"))
        self.comboFormat.setItemText(2, _translate("Dialog", ".acc"))
        self.pushClear.setText(_translate("Dialog", "Limpiar"))
        self.pushSelectDir.setText(_translate("Dialog", "Seleccionar Carpeta"))
        self.pushDownload.setText(_translate("Dialog", "Descargar Archivo"))
        self.pushOpen.setText(_translate("Dialog", "Mostar Archivo"))
        self.label_7.setText(_translate("Dialog", "Desarrollado Por: Emilio Lucero Loza"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_radioVerdeGui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
